@ktpm_backend_master_HostAddress = http://localhost:5174

POST {{ktpm_backend_master_HostAddress}}/api/user/login
Content-Type: application/json

{
    "email": "test123@gmail.com",
    "password": "123456"
}

###

GET {{ktpm_backend_master_HostAddress}}/api/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InV2UXFTVjRTUmhyVGpZSm4iLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3loeWlwZ3NueGppam1xc3pxaGx1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIzMDM2MjViMS0xM2QwLTRlMzMtODRiOC01MzFlNzI0NTMyYjQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY0ODU4ODA4LCJpYXQiOjE3NjQ4NTUyMDgsImVtYWlsIjoidGVzdDEyM0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc2NDg1NTIwOH1dLCJzZXNzaW9uX2lkIjoiMzEyMjMwZWQtYjZmMC00Njg5LTkxYTItMThmMmIyNWFmMzlkIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.BqWDO7gh2GoN1Tfq4IrjiL6Jb8bHGKJqfZ7QYHohieI

###

GET {{ktpm_backend_master_HostAddress}}/api/course/dd4a7772-e8c7-4447-a230-dce43836df91
Content-Type: application/json

###
GET {{ktpm_backend_master_HostAddress}}/api/course/folder/dd4a7772-e8c7-4447-a230-dce43836df91
Content-Type: application/json

###
GET {{ktpm_backend_master_HostAddress}}/api/course/quiz/fbb7075a-8a04-405c-989d-010183f66ef9/get
Content-Type: application/json