@ktpm_backend_master_HostAddress = http://localhost:5174

POST {{ktpm_backend_master_HostAddress}}/api/user/login
Content-Type: application/json

{
    "email": "test123@gmail.com",
    "password": "123456"
}

###

GET {{ktpm_backend_master_HostAddress}}/api/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InV2UXFTVjRTUmhyVGpZSm4iLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3loeWlwZ3NueGppam1xc3pxaGx1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIzMDM2MjViMS0xM2QwLTRlMzMtODRiOC01MzFlNzI0NTMyYjQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY0NzcxOTE3LCJpYXQiOjE3NjQ3NjgzMTcsImVtYWlsIjoidGVzdDEyM0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc2NDc2ODMxN31dLCJzZXNzaW9uX2lkIjoiZTdmMjY1OGQtYzZkMy00ZTcxLTkzZGYtYjJjMzBlODcyMzIwIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.C4z6bPY8Q_b9OkOZ3OoX6EOQUwgnhC9Fv1RmR3pHmN8

###

